version: "3.9"

services:
  api:
    build: .
    container_name: lyftr-api
    ports:
      - "8000:8000"
    environment:
      WEBHOOK_SECRET: testsecret
      LOG_LEVEL: INFO
      DATABASE_URL: sqlite:////data/app.db
    volumes:
      - data:/data

volumes:
  data:
